# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
      - name: build
        run: |
          npm run build
      - name: version
        run: |
          npm version patch
      - name: publish
        run: |
          npm publish
      

 
      
